MODEL:
  TYPE: anynet
  NUM_CLASSES: 10
ANYNET:
  STEM_TYPE: res_stem_in
  STEM_W: 64
  BLOCK_TYPE: res_bottleneck_block
  STRIDES: [1, 2, 2, 2]
  DEPTHS: [3, 4, 6, 3]
  WIDTHS: [256, 512, 1024, 2048]
  BOT_MULS: [0.5, 0.5, 0.5, 0.5]
  GROUP_WS: [4, 8, 16, 32]
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.025
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
TRAIN:
  DATASET: imagenet_10
  IM_SIZE: 224
  BATCH_SIZE: 1
  ROTATE: TRUE
  MASK_CORNERS: True
  WEIGHTS: pretrained/X-50-32x4d_dds_8gpu.pyth
  SHARED_MEM: False
TEST:
  DATASET: imagenet_10
  IM_SIZE: 256
  BATCH_SIZE: 1
  ROTATE: TRUE
  MASK_CORNERS: True
NUM_GPUS: 1
OUT_DIR: outdir/test

